services:
  beammp:
    platform: linux/arm64
    build: .
    container_name: beammp
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${PORT}:${PORT}/udp"
    environment:
      SERVER_NAME: ${SERVER_NAME}
      AUTH_KEY: ${AUTH_KEY}
      MAX_PLAYERS: ${MAX_PLAYERS}
      DESCRIPTION: ${DESCRIPTION}
      TAGS: ${TAGS}
      PRIVATE: ${PRIVATE}
      NOT_SHOW_IF_UPDATE_AVAILABLE: ${NOT_SHOW_IF_UPDATE_AVAILABLE}
      DEBUG: ${DEBUG}
      NAME: ${NAME}
      LOG_CHAT: ${LOG_CHAT}
      MAX_CARS: ${MAX_CARS}
      MAP: ${MAP}
      PORT: ${PORT}
    volumes:
      - ./mods/Server:/beammp/data/Resources/Server
      - ./mods/Client:/beammp/data/Resources/Client
    restart: unless-stopped

#volumes:
#  beammp-data:

